### ISSUE TITLE
contains? not supported using lean compilation

### ISSUE THREAD

**Issue by bruskli** [clojure-android/lein-droid#139]
Hi! Thank you for your efforts on lean clojure android compilation!
After creating a very simple project (just the template) with lein-droid, and just switching to lean compilation, the following error appears:
Exception in thread "main" java.lang.IllegalArgumentException: contains? not supported on type: clojure.lang.LazySeq, compiling:(main.clj:28:1)
	at clojure.lang.Compiler.macroexpand1(Compiler.java:6811)
	at clojure.lang.Compiler.macroexpand(Compiler.java:6869)
	at clojure.lang.Compiler.compile1(Compiler.java:7541)
	at clojure.lang.Compiler.compile1(Compiler.java:7556)
	at clojure.lang.Compiler.compile(Compiler.java:7705)
	at clojure.lang.RT.compile(RT.java:398)
	at clojure.lang.RT.load(RT.java:455)
	at clojure.lang.RT.load(RT.java:411)
	at clojure.core$load$fn__1620.invoke(core.clj:5851)
	at clojure.core$load.doInvoke(core.clj:5850)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5656)
	at clojure.core$compile$fn__1625.invoke(core.clj:5862)
	at clojure.core$compile.invoke(core.clj:5861)
	at user$eval4175.invoke(form-init5340413265018074369.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6971)
	at clojure.lang.Compiler.eval(Compiler.java:6961)
	at clojure.lang.Compiler.load(Compiler.java:7438)
	at clojure.lang.Compiler.loadFile(Compiler.java:7394)
	at clojure.main$load_script.invoke(main.clj:274)
	at clojure.main$init_opt.invoke(main.clj:279)
	at clojure.main$initialize.invoke(main.clj:307)
	at clojure.main$null_opt.invoke(main.clj:342)
	at clojure.main$main.doInvoke(main.clj:420)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:411)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:728)
	at clojure.main.main(main.java:37)
Caused by: java.lang.IllegalArgumentException: contains? not supported on type: clojure.lang.LazySeq
	at clojure.lang.RT.contains(RT.java:771)
	at clojure.core$contains_QMARK_.invoke(core.clj:1417)
	at clojure.core$generate_class$fn__2487.invoke(genclass.clj:426)
	at clojure.core$reduce1.invoke(core.clj:905)
	at clojure.core$generate_class.invoke(genclass.clj:432)
	at clojure.core$gen_class.doInvoke(genclass.clj:646)
	at clojure.lang.RestFn.invoke(RestFn.java:3705)
	at clojure.lang.Var.invoke(Var.java:677)
	at clojure.lang.AFn.applyToHelper(AFn.java:381)
	at clojure.lang.Var.applyTo(Var.java:728)
	at clojure.lang.Compiler.macroexpand1(Compiler.java:6798)
	... 28 more

I love clojure and I have very low experience with Android on clojure, but I will love to have a basis to progress with low startup times using lean compilation.

**Comment by alexander-yakushev** [comment]
That's a bug that I has been fixed some time ago. Maybe the changes haven't propagated everywhere. Please describe the exact sequence of steps that lead you to this error, thanks.

**Comment by bruskli** [comment]
Thank you Alexander,
After following the tutorial and making some changes, reflecting what I think are the latests versions of packages, I end up with the following setup:
Android SDK is updated to the latest version, including android support repository
Project.clj http://pastebin.com/1w6NYGSP
Code in the main.clj is just from the template of lein-droid

(ns brus.bubusodroid.main
    (:require [neko.activity :refer [defactivity set-content-view!]]
              [neko.debug :refer [*a]]
              [neko.notify :refer [toast]]
              [neko.resource :as res]
              [neko.find-view :refer [find-view]]
              [neko.threading :refer [on-ui]])
    (:import android.widget.EditText))

;; We execute this function to import all subclasses of R class. This gives us
;; access to all application resources.
(res/import-all)

(defn notify-from-edit
  "Finds an EditText element with ID ::user-input in the given activity. Gets
  its contents and displays them in a toast if they aren't empty. We use
  resources declared in res/values/strings.xml."
  [activity]
  (let [^EditText input (.getText (find-view activity ::user-input))]
    (toast (if (empty? input)
             (res/get-string R$string/input_is_empty)
             (res/get-string R$string/your_input_fmt input))
           :long)))

;; This is how an Activity is defined. We create one and specify its onCreate
;; method. Inside we create a user interface that consists of an edit and a
;; button. We also give set callback to the button.
(defactivity brus.bubusodroid.MainActivity
  :key :main

  (onCreate [this bundle]
    (.superOnCreate this bundle)
    (neko.debug/keep-screen-on this)
    (on-ui
      (set-content-view! (*a)
       [:linear-layout {:orientation :vertical
                        :layout-width :fill
                        :layout-height :wrap}
       [:edit-text {:id ::user-input
                    :hint "Escribe aqui"
                    :layout-width :fill}]
       [:button {:text R$string/touch_me ;; We use resource here, but could
                                           ;; have used a plain string too.
                 :on-click (fn [_] (notify-from-edit (*a)))}]]))))


Command used in building is
lein with-profile lean do clean, droid doall

Thank you for your kind support

**Comment by alexander-yakushev** [comment]
OK, you actually want skummet version 1.7.0-r1. This bug should be fixed there.

**Comment by bruskli** [comment]
Great! I don't know why I understood I needed org.skummet/clojure-android. I switched to org.skummet/clojure "1.7.0-r1", and now I have a clean and fast apk.
Thank you, and sorry for any inconvenience!

**Comment by alexander-yakushev** [comment]
You are welcome! The clojure-android version of Skummet was necessary some time ago when we had troubles with Lollipop. Now both regular Clojure, and Android builds, use org.skummet/clojure artifact.
