### ISSUE TITLE
I see warning in my REPL after i connect cider to the nrepl

### ISSUE THREAD

**Issue by sdave2** [clojure-android/lein-droid#153]
I get tthe following error.

```
WARNING: CIDER requires nREPL 0.2.12 (or newer) to work properly
         More information.
WARNING: CIDER's version (0.13.0) does not match cider-nrepl's version (nil). Things will break!
         More information.
WARNING: clj-refactor and refactor-nrepl are out of sync.
Their versions are 2.3.0-SNAPSHOT (package: 20160621.902) and n/a, respectively.
You can mute this warning by changing cljr-suppress-middleware-warnings.
```

I create a new project by running the command:
`lein new droid anfocal com.lambdacat.anfocal :activity AnFocalActivity :target-sdk 23 :app-name AnFocal`

I build and deploy it to my *emulator* by running:
`lein droid doall`

I connect to it `M-x cider-connect`, i see the error I mentioned above in my repl.

My project.clj file is:
```
(defproject anfocal/anfocal "0.1.0-SNAPSHOT"
  :description "FIXME: Android project description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}

  :global-vars {clojure.core/*warn-on-reflection* true}

  :source-paths ["src/clojure" "src"]
  :java-source-paths ["src/java"]
  :javac-options ["-target" "1.6" "-source" "1.6" "-Xlint:-options"]
  :plugins [[lein-droid "0.4.4"]]

  :dependencies [[org.clojure-android/clojure "1.7.0-r4"]
                 [neko/neko "4.0.0-alpha5"]]
  :profiles {:default [:dev]

             :dev
             [:android-common :android-user
              {:dependencies [[org.clojure/tools.nrepl "0.2.10"]]
               :target-path "target/debug"
               :android {:aot :all-with-unused
                         :manifest-options {:app-name "AnFocal (debug)"}
                         ;; Uncomment to be able install debug and release side-by-side.
                         ;; :rename-manifest-package "com.lambdacat.anfocal.debug"
                         }}]
             :release
             [:android-common
              {:target-path "target/release"
               :android
               {;; :keystore-path "/home/user/.android/private.keystore"
                ;; :key-alias "mykeyalias"
                ;; :sigalg "MD5withRSA"

                :use-debug-keystore true
                :ignore-log-priority [:debug :verbose]
                :aot :all
                :build-type :release}}]

             :lean
             [:release
              {:dependencies ^:replace [[org.skummet/clojure "1.7.0-r2"]
                                        [neko/neko "4.0.0-alpha5"]]
               :exclusions [[org.clojure/clojure]
                            [org.clojure-android/clojure]]
               :jvm-opts ["-Dclojure.compile.ignore-lean-classes=true"]
               :android {:lean-compile true
                         :proguard-execute true
                         :proguard-conf-path "build/proguard-minify.cfg"}}]}

  :android {;; Specify the path to the Android SDK directory.
            :sdk-path "/Users/default/Library/Android/sdk/"

            ;; Increase this value if dexer fails with OutOfMemoryException.
            :dex-opts ["-JXmx4096M" "--incremental"]
            
            :target-version "23"
            })
```
Java Version:
```
$ java -version
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)
```

Cider Version:
0.13.0

Maybe the version of cider I am running cannot connect to the nrepl/cider-nrepl becase of versoin mismatch?
(I couldn't download and install an older version of cider).

Any help would be awesome!
Thanks.

**Comment by sdave2** [comment]
I am going to leave the error stack trace.

```
$ lein droid doall
(Warning: profile :android-user not found.)
Generating manifest...
Generating R.java files...
(Warning: profile :android-common not found.)
(Warning: profile :android-user not found.)
Compiling 3 source files to /Users/sdave/sandbox/dirtbox/anfocal/target/debug/classes
Compiling Clojure files...
Build type: debug, dynamic compilation: enabled, remote REPL: enabled.
Compiling cider.inlined-deps.cljfmt.v0v5v3.rewrite-clj.v0v4v12.rewrite-clj.node.keyword
Compiling cider.nrepl.middleware.out
Exception in thread "main" java.lang.RuntimeException: Unable to resolve var: clojure.instant/thread-local-utc-date-format in this context, compiling:(cider/inlined_deps/fipp/v0v6v5/fipp/ednize.clj:58:13)
       	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6740)
       	at clojure.lang.Compiler.analyze(Compiler.java:6534)
       	at clojure.lang.Compiler.analyze(Compiler.java:6495)
       	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3801)
       	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6735)
       	at clojure.lang.Compiler.analyze(Compiler.java:6534)
       	at clojure.lang.Compiler.access$300(Compiler.java:38)
       	at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:6139)
       	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6733)
       	at clojure.lang.Compiler.analyze(Compiler.java:6534)
       	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6721)
       	at clojure.lang.Compiler.analyze(Compiler.java:6534)
       	at clojure.lang.Compiler.analyze(Compiler.java:6495)
       	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5871)
       	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5306)
       	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3935)
       	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6731)
       	at clojure.lang.Compiler.analyze(Compiler.java:6534)
       	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6721)
       	at clojure.lang.Compiler.analyze(Compiler.java:6534)
       	at clojure.lang.Compiler.analyze(Compiler.java:6495)
       	at clojure.lang.Compiler$MapExpr.parse(Compiler.java:3060)
       	at clojure.lang.Compiler.analyze(Compiler.java:6542)
       	at clojure.lang.Compiler.analyze(Compiler.java:6495)
       	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3801)
       	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6735)
       	at clojure.lang.Compiler.analyze(Compiler.java:6534)
       	at clojure.lang.Compiler.analyze(Compiler.java:6495)
       	at clojure.lang.Compiler.compile1(Compiler.java:7328)
       	at clojure.lang.Compiler.compile1(Compiler.java:7323)
       	at clojure.lang.Compiler.compile(Compiler.java:7400)
       	at clojure.lang.RT.compile(RT.java:408)
       	at clojure.lang.RT.load(RT.java:456)
       	at clojure.lang.RT.load(RT.java:421)
       	at clojure.core$load$fn__5458.invoke(core.clj:5862)
       	at clojure.core$load.doInvoke(core.clj:5861)
       	at clojure.lang.RestFn.invoke(RestFn.java:408)
       	at clojure.core$load_one.invoke(core.clj:5667)
       	at clojure.core$load_lib$fn__5407.invoke(core.clj:5707)
       	at clojure.core$load_lib.doInvoke(core.clj:5706)
       	at clojure.lang.RestFn.applyTo(RestFn.java:142)
       	at clojure.core$apply.invoke(core.clj:632)
       	at clojure.core$load_libs.doInvoke(core.clj:5745)
       	at clojure.lang.RestFn.applyTo(RestFn.java:137)
       	at clojure.core$apply.invoke(core.clj:632)
       	at clojure.core$require.doInvoke(core.clj:5828)
       	at clojure.lang.RestFn.invoke(RestFn.java:436)
       	at cider.inlined_deps.fipp.v0v6v5.fipp.edn$loading__5350__auto____955.invoke(edn.cljc:1)
       	at clojure.lang.AFn.applyToHelper(AFn.java:152)
       	at clojure.lang.AFn.applyTo(AFn.java:144)
       	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3633)
       	at clojure.lang.Compiler.compile1(Compiler.java:7333)
       	at clojure.lang.Compiler.compile1(Compiler.java:7323)
       	at clojure.lang.Compiler.compile(Compiler.java:7400)
       	at clojure.lang.RT.compile(RT.java:408)
       	at clojure.lang.RT.load(RT.java:456)
       	at clojure.lang.RT.load(RT.java:421)
       	at clojure.core$load$fn__5458.invoke(core.clj:5862)
       	at clojure.core$load.doInvoke(core.clj:5861)
       	at clojure.lang.RestFn.invoke(RestFn.java:408)
       	at clojure.core$load_one.invoke(core.clj:5667)
       	at clojure.core$load_lib$fn__5407.invoke(core.clj:5707)
       	at clojure.core$load_lib.doInvoke(core.clj:5706)
       	at clojure.lang.RestFn.applyTo(RestFn.java:142)
       	at clojure.core$apply.invoke(core.clj:632)
       	at clojure.core$load_libs.doInvoke(core.clj:5745)
       	at clojure.lang.RestFn.applyTo(RestFn.java:137)
       	at clojure.core$apply.invoke(core.clj:632)
       	at clojure.core$require.doInvoke(core.clj:5828)
       	at clojure.lang.RestFn.invoke(RestFn.java:930)
       	at cider.nrepl.middleware.pprint$loading__5350__auto____471.invoke(pprint.clj:1)
       	at clojure.lang.AFn.applyToHelper(AFn.java:152)
       	at clojure.lang.AFn.applyTo(AFn.java:144)
       	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3633)
       	at clojure.lang.Compiler.compile1(Compiler.java:7333)
       	at clojure.lang.Compiler.compile1(Compiler.java:7323)
       	at clojure.lang.Compiler.compile(Compiler.java:7400)
       	at clojure.lang.RT.compile(RT.java:408)
       	at clojure.lang.RT.load(RT.java:456)
       	at clojure.lang.RT.load(RT.java:421)
       	at clojure.core$load$fn__5458.invoke(core.clj:5862)
       	at clojure.core$load.doInvoke(core.clj:5861)
       	at clojure.lang.RestFn.invoke(RestFn.java:408)
       	at clojure.core$load_one.invoke(core.clj:5667)
       	at clojure.core$load_lib$fn__5407.invoke(core.clj:5707)
       	at clojure.core$load_lib.doInvoke(core.clj:5706)
       	at clojure.lang.RestFn.applyTo(RestFn.java:142)
       	at clojure.core$apply.invoke(core.clj:632)
       	at clojure.core$load_libs.doInvoke(core.clj:5745)
       	at clojure.lang.RestFn.applyTo(RestFn.java:137)
       	at clojure.core$apply.invoke(core.clj:632)
       	at clojure.core$require.doInvoke(core.clj:5828)
       	at clojure.lang.RestFn.invoke(RestFn.java:619)
       	at cider.nrepl.middleware.stacktrace$loading__5350__auto____469.invoke(stacktrace.clj:1)
       	at clojure.lang.AFn.applyToHelper(AFn.java:152)
       	at clojure.lang.AFn.applyTo(AFn.java:144)
       	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3633)
       	at clojure.lang.Compiler.compile1(Compiler.java:7333)
       	at clojure.lang.Compiler.compile1(Compiler.java:7323)
       	at clojure.lang.Compiler.compile(Compiler.java:7400)
       	at clojure.lang.RT.compile(RT.java:408)
       	at clojure.lang.RT.load(RT.java:456)
       	at clojure.lang.RT.load(RT.java:421)
       	at clojure.core$load$fn__5458.invoke(core.clj:5862)
       	at clojure.core$load.doInvoke(core.clj:5861)
       	at clojure.lang.RestFn.invoke(RestFn.java:408)
       	at clojure.core$load_one.invoke(core.clj:5667)
       	at clojure.core$load_lib$fn__5407.invoke(core.clj:5707)
       	at clojure.core$load_lib.doInvoke(core.clj:5706)
       	at clojure.lang.RestFn.applyTo(RestFn.java:142)
       	at clojure.core$apply.invoke(core.clj:632)
       	at clojure.core$load_libs.doInvoke(core.clj:5745)
       	at clojure.lang.RestFn.applyTo(RestFn.java:137)
       	at clojure.core$apply.invoke(core.clj:632)
       	at clojure.core$require.doInvoke(core.clj:5828)
       	at clojure.lang.RestFn.invoke(RestFn.java:512)
       	at cider.nrepl.middleware.util.error_handling$loading__5350__auto____262.invoke(error_handling.clj:1)
       	at clojure.lang.AFn.applyToHelper(AFn.java:152)
       	at clojure.lang.AFn.applyTo(AFn.java:144)
       	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3633)
       	at clojure.lang.Compiler.compile1(Compiler.java:7333)
       	at clojure.lang.Compiler.compile1(Compiler.java:7323)
       	at clojure.lang.Compiler.compile(Compiler.java:7400)
       	at clojure.lang.RT.compile(RT.java:408)
       	at clojure.lang.RT.load(RT.java:456)
       	at clojure.lang.RT.load(RT.java:421)
       	at clojure.core$load$fn__5458.invoke(core.clj:5862)
       	at clojure.core$load.doInvoke(core.clj:5861)
       	at clojure.lang.RestFn.invoke(RestFn.java:408)
       	at clojure.core$load_one.invoke(core.clj:5667)
       	at clojure.core$load_lib$fn__5407.invoke(core.clj:5707)
       	at clojure.core$load_lib.doInvoke(core.clj:5706)
       	at clojure.lang.RestFn.applyTo(RestFn.java:142)
       	at clojure.core$apply.invoke(core.clj:632)
       	at clojure.core$load_libs.doInvoke(core.clj:5745)
       	at clojure.lang.RestFn.applyTo(RestFn.java:137)
       	at clojure.core$apply.invoke(core.clj:632)
       	at clojure.core$require.doInvoke(core.clj:5828)
       	at clojure.lang.RestFn.invoke(RestFn.java:512)
       	at cider.nrepl.middleware.out$loading__5350__auto____235.invoke(out.clj:1)
       	at clojure.lang.AFn.applyToHelper(AFn.java:152)
       	at clojure.lang.AFn.applyTo(AFn.java:144)
       	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3633)
       	at clojure.lang.Compiler.compile1(Compiler.java:7333)
       	at clojure.lang.Compiler.compile1(Compiler.java:7323)
       	at clojure.lang.Compiler.compile(Compiler.java:7400)
       	at clojure.lang.RT.compile(RT.java:408)
       	at clojure.lang.RT.load(RT.java:456)
       	at clojure.lang.RT.load(RT.java:421)
       	at clojure.core$load$fn__5458.invoke(core.clj:5862)
       	at clojure.core$load.doInvoke(core.clj:5861)
       	at clojure.lang.RestFn.invoke(RestFn.java:408)
       	at clojure.core$load_one.invoke(core.clj:5667)
       	at clojure.core$compile$fn__5463.invoke(core.clj:5873)
       	at clojure.core$compile.invoke(core.clj:5872)
       	at user$eval5.invoke(form-init1210799583007971841.clj:1)
       	at clojure.lang.Compiler.eval(Compiler.java:6792)
       	at clojure.lang.Compiler.eval(Compiler.java:6782)
       	at clojure.lang.Compiler.load(Compiler.java:7237)
       	at clojure.lang.Compiler.loadFile(Compiler.java:7175)
       	at clojure.main$load_script.invoke(main.clj:280)
       	at clojure.main$init_opt.invoke(main.clj:285)
       	at clojure.main$initialize.invoke(main.clj:313)
       	at clojure.main$null_opt.invoke(main.clj:348)
       	at clojure.main$main.doInvoke(main.clj:426)
       	at clojure.lang.RestFn.invoke(RestFn.java:421)
       	at clojure.lang.Var.invoke(Var.java:383)
       	at clojure.lang.AFn.applyToHelper(AFn.java:156)
       	at clojure.lang.Var.applyTo(Var.java:700)
       	at clojure.main.main(main.java:37)
Caused by: java.lang.RuntimeException: Unable to resolve var: clojure.instant/thread-local-utc-date-format in this context
       	at clojure.lang.Util.runtimeException(Util.java:221)
       	at clojure.lang.Compiler$TheVarExpr$Parser.parse(Compiler.java:698)
       	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6733)
       	... 169 more
Compilation failed.
```

**Comment by sdave2** [comment]
ping!

**Comment by satchit8** [comment]
FWIW, I've gotten those types of warnings when starting Cider as far back as I 
can remember (at least when using it with Clojure on Android) and have not 
succeeded in getting them to go away.  Having said that, whatever Cider 
functionality that remains has been helpful enough.

I'd be happy to see the warnings go away too :)

On a side note, I've been using monroe with some success:

  https://github.com/sanel/monroe/

**Comment by nyrell** [comment]
Hi, 

did anyone ever solve the problem with the CIDER warnings? I have the very same problem (for cider-15-snapshot) and started a thread in the clojure-android mailing list to try to work it out.

https://groups.google.com/forum/#!topic/clojure-android/eK5_tU6Uyno

Thanks for the link to the monroe project above. If I don't get cider to work I will look into that instead.

/Mattias Nyrell
