### ISSUE TITLE
problems with using [cider/cider-nrepl "0.15.0"]

### ISSUE THREAD

**Issue by sonwh98** [clojure-android/lein-droid#164]
this problem doesn't happen if I use cider-nrepl "0.9.1" or "0.10.0" . I can use these versions but will have to downgrade cider or get warnings about incompatible versions

here's my profile.clj 
```clojure
{:android-user {:dependencies [[cider/cider-nrepl "0.15.0"]]
                :android {:aot-exclude-ns ["cider.nrepl.middleware.util.java.parser"
                                           "cider.nrepl" "cider-nrepl.plugin"]}}}```

Here's the stack trace when running lein droid build:

Compiling cider.nrepl.middleware.debug
Reflection warning, cider/nrepl/middleware/pprint.clj:91:3 - reference to field close can't be resolved.
Reflection warning, cider/nrepl/middleware/stacktrace.clj:90:19 - reference to field isDirectory can't be resolved.
Reflection warning, cider/nrepl/middleware/stacktrace.clj:88:31 - call to method endsWith can't be resolved (target class is unknown).
Reflection warning, cider/nrepl/middleware/util/meta.clj:182:36 - reference to field read can't be resolved.
Reflection warning, cider/nrepl/middleware/util/meta.clj:189:28 - call to method unread can't be resolved (target class is unknown).
Exception in thread "main" java.lang.RuntimeException: No such var: u/update-vals, compiling:(cider/nrepl/middleware/util/meta.clj:286:8)
        at clojure.lang.Compiler.analyze(Compiler.java:6553)
        at clojure.lang.Compiler.analyze(Compiler.java:6495)
        at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3747)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6735)
        at clojure.lang.Compiler.analyze(Compiler.java:6534)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6721)
        at clojure.lang.Compiler.analyze(Compiler.java:6534)
        at clojure.lang.Compiler.analyze(Compiler.java:6495)
        at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5871)
        at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5306)
        at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3935)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6731)
        at clojure.lang.Compiler.analyze(Compiler.java:6534)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6721)
        at clojure.lang.Compiler.analyze(Compiler.java:6534)
        at clojure.lang.Compiler.access$300(Compiler.java:38)
        at clojure.lang.Compiler$DefExpr$Parser.parse(Compiler.java:577)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6733)
        at clojure.lang.Compiler.analyze(Compiler.java:6534)
        at clojure.lang.Compiler.analyze(Compiler.java:6495)
        at clojure.lang.Compiler.compile1(Compiler.java:7328)
        at clojure.lang.Compiler.compile(Compiler.java:7400)
        at clojure.lang.RT.compile(RT.java:408)
        at clojure.lang.RT.load(RT.java:456)
        at clojure.lang.RT.load(RT.java:421)
        at clojure.core$load$fn__5458.invoke(core.clj:5862)
        at clojure.core$load.doInvoke(core.clj:5861)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invoke(core.clj:5667)
	at clojure.core$load_lib$fn__5407.invoke(core.clj:5707)
	at clojure.core$load_lib.doInvoke(core.clj:5706)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:632)
	at clojure.core$load_libs.doInvoke(core.clj:5745)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:632)
	at clojure.core$require.doInvoke(core.clj:5828)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at cider.nrepl.middleware.util.instrument$loading__5350__auto____2673.invoke(instrument.clj:1)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3633)
	at clojure.lang.Compiler.compile1(Compiler.java:7333)
	at clojure.lang.Compiler.compile1(Compiler.java:7323)
	at clojure.lang.Compiler.compile(Compiler.java:7400)
	at clojure.lang.RT.compile(RT.java:408)
	at clojure.lang.RT.load(RT.java:456)
	at clojure.lang.RT.load(RT.java:421)
	at clojure.core$load$fn__5458.invoke(core.clj:5862)
	at clojure.core$load.doInvoke(core.clj:5861)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5667)
	at clojure.core$load_lib$fn__5407.invoke(core.clj:5707)
	at clojure.core$load_lib.doInvoke(core.clj:5706)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:632)
	at clojure.core$load_libs.doInvoke(core.clj:5745)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:632)
	at clojure.core$require.doInvoke(core.clj:5828)
	at clojure.lang.RestFn.invoke(RestFn.java:2088)
	at cider.nrepl.middleware.debug$loading__5350__auto____2184.invoke(debug.clj:1)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3633)
	at clojure.lang.Compiler.compile1(Compiler.java:7333)
	at clojure.lang.Compiler.compile1(Compiler.java:7323)
	at clojure.lang.Compiler.compile(Compiler.java:7400)
	at clojure.lang.RT.compile(RT.java:408)
	at clojure.lang.RT.load(RT.java:456)

**Comment by sonwh98** [comment]
figured it out. need to put [cider/cider-nrepl "0.15.0"] as a dependency in project.clj as well. the docs should reflect this

**Comment by sonwh98** [comment]
actually this didn't fix it. i think what happened was i built with cider-nrepl "0.10.0" then didn't do a clean so it looked like it worked.
