### ISSUE TITLE
release build causes java.io.FileNotFoundException: Could not locate clojure/tools/nrepl/server__init.class

### ISSUE THREAD

**Issue by thash** [clojure-android/lein-droid#81]
Hi.
First I must thank you for this great project. I'm really enjoying making Android app in Clojure.

Yesterday I faced release build problem. Following procedure is the reproduction of my problem.

```
$ lein --version
Leiningen 2.3.2 on Java 1.7.0_25 Java HotSpot(TM) 64-Bit Server VM

$ cat ~/.lein/profiles.clj
{:user  {:plugins  [[lein-droid "0.2.0-preview4"]
...
```

> ;; I'm using 0.2.0-preview4 because latest 0.2.0 cause another problem.
> ;; When I execute `lein droid new` and `lein droid doall` with 0.2.0, launched app is killed instantly by `java.lang.ClassNotFoundException` for SplashActivity.

First, create project and debug build.

```
$ lein droid new clojure-android-release-test com.memerelics.release_test
$ cd clojure-android-release-test
$ lein droid doall
```

It runs correctly on my device.

Then generate key to sign apk, and edit project.clj to use it.

```
$ keytool -genkey -keyalg RSA -v -keystore ~/.keystore -alias test -validity 365
$ edit project.clj
```

``` clj
  :dependencies [[org.clojure-android/clojure "1.5.1-jb" :use-resources true]
                 [neko/neko "3.0.0-preview3"]]
  :profiles {:dev {:dependencies [[android/tools.nrepl "0.2.0-bigstack"]
                                  [compliment "0.0.2"]]
                   :android {:aot :all-with-unused}}
             :release {:android
                       {:keystore-path "/Users/username/.keystore" ;; add
                        :key-alias "test" ;; add
...
```

Finally, I built and run the project as a release version.

```
$ lein droid release

E/AndroidRuntime( 7579): java.io.FileNotFoundException: Could not locate clojure/tools/nrepl/server__init.class or clojure/tools/nrepl/server.clj on classpath:
E/AndroidRuntime( 7579):        at clojure.lang.RT.load(RT.java:468)
E/AndroidRuntime( 7579):        at clojure.lang.RT.load(RT.java:436)
E/AndroidRuntime( 7579):        at clojure.core$load$fn__5018.invoke(core.clj:5529)
E/AndroidRuntime( 7579):        at clojure.core$load.doInvoke(core.clj:5529)
E/AndroidRuntime( 7579):        at clojure.lang.RestFn.invoke(RestFn.java:408)
E/AndroidRuntime( 7579):        at clojure.core$load_one.invoke(core.clj:5336)
E/AndroidRuntime( 7579):        at clojure.core$load_lib$fn__4967.invoke(core.clj:5374)
E/AndroidRuntime( 7579):        at clojure.core$load_lib.doInvoke(core.clj:5374)
E/AndroidRuntime( 7579):        at clojure.lang.RestFn.applyTo(RestFn.java:142)
E/AndroidRuntime( 7579):        at clojure.core$apply.invoke(core.clj:619)
E/AndroidRuntime( 7579):        at clojure.core$load_libs.doInvoke(core.clj:5413)
E/AndroidRuntime( 7579):        at clojure.lang.RestFn.applyTo(RestFn.java:137)
E/AndroidRuntime( 7579):        at clojure.core$apply.invoke(core.clj:621)
E/AndroidRuntime( 7579):        at clojure.core$use.doInvoke(core.clj:5498)
E/AndroidRuntime( 7579):        at clojure.lang.RestFn.invoke(RestFn.java:408)
E/AndroidRuntime( 7579):        at neko.init$start_repl.doInvoke(init.clj:36)
E/AndroidRuntime( 7579):        at clojure.lang.RestFn.applyTo(RestFn.java:137)
E/AndroidRuntime( 7579):        at clojure.core$apply.invoke(core.clj:621)
E/AndroidRuntime( 7579):        at neko.init$init.doInvoke(init.clj:80)
E/AndroidRuntime( 7579):        at clojure.lang.RestFn.invoke(RestFn.java:410)
E/AndroidRuntime( 7579):        at clojure.lang.Var.invoke(Var.java:415)
E/AndroidRuntime( 7579):        at com.memerelics.release_test.SplashActivity$1.run(SplashActivity.java:62)
E/AndroidRuntime( 7579):        at java.lang.Thread.run(Thread.java:856)
```

The logcat message says my app could not find nrepl server. Release build also require nrepl? Or I've missed some settings?

**Comment by konmik** [comment]
Just for notice:

 I get this error because of Kaspersky Antivirus. It suspects the generated classes.dex

**Comment by alexander-yakushev** [comment]
Thanks for pointing it out. I don't think there's anything that can be done about it on Leiningen's side, but still good to know.
